### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by MikaKC** [MoldyMacaroniX/gd-website#29]
I find it very unpractical to have the search bar as a pop-up.

**Instead**
I would have it next to the magnifying glass and do the pop-up with the searched keywords once the person presses enter.

**Comment by MoldyMacaroniX** [comment]
Not sure if this is a super big priority. I think its fine right now but this is definitely an option to consider down the line. I'd like to hear what others think.

**Comment by MoldyMacaroniX** [comment]
Going to close this now but we can reopen later if need be.
