### ISSUE TITLE
[FEATURE REQUEST] ALL images are hosted on imgur (or other image hosting services)

### ISSUE THREAD

**Issue by fgclue** [MoldyMacaroniX/gd-website#63]
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to a problem. 

**Describe the solution you'd like**
I'd like if the images where hosted in the website itself.

**Would it take space?**
Yes, of course.

**Describe alternatives you've considered**
(This is not a good idea) 
You could store the images on GitHub.

**Additional context**
I don't really have anything to say, so I'm just going to end this feature request here. i forgor 💀

**Comment by MikaKC** [comment]
Could you like elaborate as to why using external image hosting is worse?

**Comment by fgclue** [comment]
yea

**Comment by MoldyMacaroniX** [comment]
I know this is closed but this is a valid issue. Most images are referenced from other sources which is not a very long term solution. The problem is that there really isn't a good alternative in the moment.

Maybe down the line I can find a way to monetize the site and pay for our own CDN.
